apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      name: goserver
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: emmanuelviniciusdev/imersao-fullcycle-k8s-hello-k8s:v8
          envFrom:
            - configMapRef:
                name: goserver-configmap
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - mountPath: "/go/src/app/countries"
              name: volume-countries
      volumes:
        - name: volume-countries
          configMap:
            name: goserver-configmap-countries
            items:
              - key: countries
                path: "countries.txt"