apiVersion: v1
kind: Service
metadata:
  name: goserver-service-clusterip
spec:
  type: ClusterIP
  selector:
    app: goserver
  ports:
    - name: goserver-service
      port: 8080
      protocol: TCP
