apiVersion: v1
kind: Service
metadata:
  name: goserver-service-nodeport
spec:
  type: NodePort
  selector:
    app: goserver
  ports:
    - name: goserver-service
      port: 8080
      nodePort: 30001
      protocol: TCP
