apiVersion: v1
kind: Service
metadata:
  name: goserver-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: goserver
  ports:
    - name: goserver-service-loadbalancer
      port: 8080
      protocol: TCP
